name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP with version 8.1 (update PHP to 8.1 as recommended)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Disarankan untuk PHP 8.1 atau lebih baru

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    # Give execute permission to PHPUnit
    - name: Give PHPUnit execute permission
      run: chmod +x vendor/phpunit/phpunit/phpunit

    # Run tests using the custom PHPUnit path
    - name: Run PHPUnit Tests
      run: |
        if [ -f vendor/phpunit/phpunit/phpunit ]; then
          vendor/phpunit/phpunit/phpunit --configuration phpunit.xml
        else
          echo "No PHPUnit tests found."
        fi

    # Deployment step (example for cPanel deployment)
    - name: Deploy to cPanel
      run: |
        # Use FTP or SSH to deploy to cPanel server, or add your deployment command here
        echo "Deploying to server..."
